User.java

Bakes communication into our design; made more sense to the team object-wise.

Update and rename Terminal.java to User.java

---

ChocAn.java
Main.java
Utility.java

Got the login function down and checking for the correct input. I'll be working on a switch case to handle the user  status returned by the Login function (that calls on DataAccess).  I have the Utility class acting as a little toolbox of a Scanner object and some functions that may be reused throughout the ChocAn terminal. I also added a Main, so the an instance of Chocan can be called and it will call one function "run()".  This will keep our main at about 5 lines---clean and simple.

The Login function for the Terminal is complete; created a Utility class; created Main.

---

ChocAn.java
Main.java
Manager.java
Provider.java
User.java

Some basic changes to the user hierarchy. Changed User to abstract
class. Added abstract displayUserInfo function that gets implemented in
derived manager and provider classes. Can be used to display basic user
variables. Added some variables to the provider class.

Changes to user hierarchy

---

ChocAn.java
Utility.java

defineUserRole:
switch statement handled to allow user to proceed to appropriate menu or get kicked out if they're not a manager or provider
checkAnswer:
(in the utility class)
Converted return type to int to allow for a more robust error check. It now handles all types of input: yes, no, or invalid input.

userDefineRole & checkAnswer

---

Main.java
Manager.java
User.java

Changed User back to abstract and uses run instead of main for function
calls. Nothing in the run() function yet.

Changes to manager/provider class

---

ChocAn.java
Utility.java

Resolved unexpected behaviors & error response to user input.

Updates to Utility & ChocAn

---

Manager.java
User.java

So... after much toil and trouble I have implemented some new functions
under manager and Matty so graciously updated the way manager input is
presented and handled by implementing a displayMenu function that
captures the managers input which runs the corresponding function under
run().

Manager Updates

---

Manager.java

+ Commented out clearScreen() & waitForEnter code (unstable)
+ menuPrompt()
Menu Input now handles case where user inputs chars & strings
+editSubmenu()
Submenu Input now handles case where user inputs chars & strings
+ addOrganization()
Zip code Input now handles case where user inputs chars & strings
+ changMemberStanding()
Member ID Input now handles case where user inputs chars & strings

Manager User Input: Integer Check

---

Manager.java
Utility.java

Changed a few functions. addOrganization now handles both provider and
member as one function instead of having two separate functions,
addMember() and addProvider(). Added promptString() and promptInt()
functions for input. Added removeOrganization() as one function to
remove a provider or a member. Added input.nextLine() in Utility
checkAnswer() function to consume \n character for input.

Changes to manager class and one change to utility class

---

Provider.java

Only Provider.java has been changed. 
This update fixes how input is taken in with Provider functions (adding input.nextLine() calls). Additionally, input is now shown on the same line as prompts, (previous versions had input shown below the prompt)

Updated provider (input fixes)

---

Manager.java

Changed changeMemberStanding() to call appropriate DataAccess suspend/unsuspendMember functions. Got rid of Manager version of suspendMember()/unsuspendMember() since they are not necessary due to the change to changeMemberStanding(). Updated promptInt() to perform integer input check inside the function. Removed lines of code where we were doing this check for the zip code input and added call to promptInt() for the zip code instead.

Manager updateorganization

---

Manager.java
Provider.java
Utility.java

I added new readInt(String prompt,String errorMessage) and readString(String prompt) where you can just the prompt and get user's input without doing the system.out and input.next
shrunk the code by a lot

Added New readInt and readString

---

Manager.java
Provider.java
Utility.java

Added three messages functions, errorMessage, waringMessage, successMessage in the utility class

ErrorMessages functions

---

Manager.java

Changed the variable remove in removeOrganization to userToRemove.

Changed variable name.

---

Provider.java

Provider now handles non-numerical input when not expected
Provider now has clear screens where appropriate (please run and verify)

Provider updates

---

Manager.java

Prompt error when user entered incorrect data, prompt for their choice didn't show up.

Manager Edit Submenu

---

Provider.java

Same fix as the Manager Edit Submenu; just needed to swap the arguments for readINt()

Provider Menu Error

---

Provider.java

Fixed provider prompts and had verifyMember() return true on a suspended member instead of false

Provider prompt fixes

---

ChocAn.java
DataAccess.java
Main.java
Manager.java
Organization.java
Provider.java
User.java
Utility.java

Cleaned up the code in most files. Got rid of commented out code.
Changed a few menu related things. Blah blah blah.

Cleaned up code

---

ChocAn.java
DataAccess.java
Main.java
Manager.java
Organization.java
Provider.java
ServiceReport.java
User.java
Utility.java

Some last minute minor changes including:
1. Slight syntax changes to maintain consistency with Java standards
2. Removal of some more commented code found throughout the project.
3. Addition of some comments to explain certain things.

Minor changes
